### ISSUE TITLE
problem with `jupyter nbextension install --py nbzip'

### ISSUE THREAD

**Issue by malej** [data-8/nbzip#9]
I seem to have the same problem on two different machines (Mac and Linux) with the second line in the installation process. Does one need to do it as a root -- sudo doesn't work? Not sure why it is trying to write to `/usr/local/share/jupyter` ... there is only `kernels` directory there (no nbextensions directory there at all. 

Any suggestions? See below:

`
 ~ $ jupyter nbextension install --py nbzip
Installing /home/rdchlmm9/anaconda3/lib/python3.6/site-packages/nbzip/static -> nbzip
Traceback (most recent call last):
  File "/home/rdchlmm9/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/rdchlmm9/anaconda3/lib/python3.6/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/rdchlmm9/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbextensions'

 ~ $ sudo jupyter nbextension install --py nbzip
sudo: jupyter: command not found

~ $ jupyter nbextension enable --py nbzip
Enabling tree extension nbzip/tree...
      - Validating: problems found:
        - require?  X nbzip/tree
`

**Comment by SaladRaider** [comment]
@malej Sorry about that. It seems that I accidentally uploaded the package to PyPI with a bad setup file. I fixed it, and I think it should work now.

**Comment by hagi123456** [comment]
Unfortunately, I still have this error. I install both with pip and from this repository.
